wandb_version: 1

hidden_dim:
  desc: null
  value: 128
batch_size:
  desc: null
  value: 4096
mini_batch_size:
  desc: null
  value: 128
use_minibatch:
  desc: null
  value: true
lr:
  desc: null
  value: 0.0009
gamma:
  desc: null
  value: 0.99
epsilon:
  desc: null
  value: 0.05
use_state_norm:
  desc: null
  value: false
use_reward_scaling:
  desc: null
  value: true
entropy_coef:
  desc: null
  value: 0.01
device:
  desc: null
  value: cpu
layout:
  desc: null
  value: cramped_room
num_episodes:
  desc: null
  value: 3000
seed:
  desc: null
  value: 11
max_episode_steps:
  desc: null
  value: 600
state_dim:
  desc: null
  value: 96
action_dim:
  desc: null
  value: 6
_wandb:
  desc: null
  value:
    python_version: 3.7.12
    cli_version: 0.15.12
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1699617422.767594
    t:
      1:
      - 1
      - 55
      2:
      - 1
      - 55
      3:
      - 2
      - 13
      - 16
      - 23
      4: 3.7.12
      5: 0.15.12
      8:
      - 5
      13: linux-x86_64
