wandb_version: 1

device:
  desc: null
  value: cuda
layout:
  desc: null
  value: cramped_room
num_episodes:
  desc: null
  value: 50
seed:
  desc: null
  value: 1
_wandb:
  desc: null
  value:
    python_version: 3.7.12
    cli_version: 0.15.12
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1699879439.195301
    t:
      1:
      - 1
      - 55
      2:
      - 1
      - 55
      3:
      - 13
      - 16
      - 23
      4: 3.7.12
      5: 0.15.12
      8:
      - 5
      13: linux-x86_64
