wandb_version: 1

device:
  desc: null
  value: cuda
layout:
  desc: null
  value: cramped_room
num_episodes:
  desc: null
  value: 100
mode:
  desc: null
  value: intra
switch_human_freq:
  desc: null
  value: 100
seed:
  desc: null
  value: 0
Q_len:
  desc: null
  value: 25
plot_group:
  desc: null
  value: BPR_NN_MOD
_wandb:
  desc: null
  value:
    python_version: 3.7.12
    cli_version: 0.15.12
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1700051237.212175
    t:
      1:
      - 1
      - 5
      - 53
      - 55
      2:
      - 1
      - 5
      - 53
      - 55
      3:
      - 13
      - 16
      - 23
      4: 3.7.12
      5: 0.15.12
      8:
      - 5
      13: linux-x86_64
